### ISSUE TITLE
--output docset

### ISSUE THREAD

**Issue by Kapeli** [neogeek/doxdox#4]
How do you use doxdox with `--layout Dash`? If I give it a file using `--output`, it seems to try to save a directory structure into it.

**Comment by neogeek** [comment]
When exporting to the Dash layout a directory structure is created within a parent folder named `<project name>.docset`, zipped and sent to either `stdout` or `--output`:

```bash
$ doxdox --layout Dash --output ~/Desktop/docset.zip
```

I'll keep this ticket open until I put together proper documentation for all of the layout types.

**Comment by Kapeli** [comment]
I tried zip before opening this issue, but when I tried unarchiving using my default archive app (Entropy), it gave an error about not being able to unarchive.

I tried again and unarchived using Archive Utility and it works fine, so all good. Might be worth considering a change to just output to a folder instead of a zip.
