### ISSUE TITLE
ignore comment types

### ISSUE THREAD

**Issue by aretecode** [neogeek/doxdox#47]
it picks up non-doc blocks which can ruin the documentation when there are a lot of them

examples:
`istanbul ignore next: dev`
`prettier-ignore`

**Comment by neogeek** [comment]
Currently doxdox ignores document blocks via this syntax <https://github.com/tj/dox#ignore>. Would it help to also add support for the [`@ignore`](http://usejsdoc.org/tags-ignore.html) tag? 

Also are these `// single line comment` or `/* single star comment */`?

**Comment by aretecode** [comment]
@neogeek the latter `/* istanbul-ignore next */` `/* prettier ignore*/`

**Comment by neogeek** [comment]
Cool. I'll take a look at this as soon as I can. Thanks!

**Comment by neogeek** [comment]
Released a fix for this with the latest version of <https://github.com/neogeek/doxdox-parser-dox/releases/tag/v1.1.3>
