### ISSUE TITLE
Why include parameters in Dash docset index?

### ISSUE THREAD

**Issue by Kapeli** [neogeek/doxdox#5]
Is this needed? Do you usually search using a parameter name? Just including the methods should be fine as far as I can tell. I don't use node though so I have no idea.

You could include them in the in-page anchors only and not inside the main search index.

**Comment by neogeek** [comment]
I had included parameters so that you can search for sub-parameters like this:

![dash](https://cloud.githubusercontent.com/assets/6753/5639060/24702780-95de-11e4-8e48-c2a016adc1d8.png)

Is there a better way to make them searchable?

**Comment by Kapeli** [comment]
Nope, that's the only way to make them searchable. My concerns were whether or not they should be searchable in the first place. None of the existing docsets allow searching of parameters.

Is there any reason why this would be useful for node packages?

**Comment by neogeek** [comment]
This is true. Perhaps it's not as necessary as I had originally thought, as they are still visible through the Table of Contents.
