### ISSUE TITLE
multi release

### ISSUE THREAD

**Issue by yesvods** [neogeek/doxdox#69]
Hi, I've seen the [doc](https://doxdox.org/neogeek/doxdox/v2.0.0) of doxdox has show entry of each releases version. How can I generate docs like that. Thanks.

![image](https://user-images.githubusercontent.com/4458848/40551289-0eb19d7a-606f-11e8-9d95-c6b8646154ce.png)

**Comment by yesvods** [comment]
closed due to no reply.

**Comment by neogeek** [comment]
This feature was built specifically for the doxdox.org website, it was not included in the bootstrap template.
