### ISSUE TITLE
List of ignored folders should be configurable

### ISSUE THREAD

**Issue by Dachaz** [neogeek/doxdox#8]
Hi there,

I was trying to compile documentation for our internal test-writing API, but `doxdox` would silently fail because, unsurprisingly, part of the path contained the word `test`. Would be nice if the list of ignored folders was configurable/overridable.

Btw, I really like the direction of doxdox — I spent several days looking into currently available solutions for converting JSDoc into something human readable, and yours is the most promising. Keep it up!

**Comment by neogeek** [comment]
Thanks! I'm really happy to hear that you are liking doxdox!

I just looked into the regular expression I have for excluding directories (and files) and I think that I could make it work a little more intelligently. Right now it's checking to see if the directory contains the word test, but it should really just be checking if the directory (or file) matches certain values.

As for adding a configurable option, I'm in the middle of a complete re-write of doxdox and that is something I will definitely be adding.

**Comment by neogeek** [comment]
The latest release of doxdox (`v0.1.13`) has improvements to the regular expression that handles the exclusion of files and directories. Let me know if this works for you until a configurable flag is added.

**Comment by Dachaz** [comment]
Yup, this works for our case — so I could remove the workaround I originally put in there when generating the docs. Thanks!

**Comment by neogeek** [comment]
The latest release of doxdox (`v1.1.0`) has support for ignorable directories and files via the CLI <https://github.com/neogeek/doxdox#ignore>.

I'm closing this issue as the feature has been implemented. If you have any issues with it feel free to open it again.

Thanks again for trying doxdox!
